import { jsPDF } from "jspdf";

const STORAGE_KEY = 'dr_care_history';

// --- SAVE TO HISTORY (Now saves User Details) ---
export const saveSession = (symptoms, diagnosis, type, userDetails) => {
  const newRecord = {
    id: Date.now(),
    date: new Date().toLocaleDateString(),
    time: new Date().toLocaleTimeString(),
    type: type, 
    symptoms: symptoms,
    diagnosis: diagnosis,
    patient: userDetails || { name: 'Unknown', age: 'N/A' } // Save patient snapshot
  };

  const existingHistory = getHistory();
  const updatedHistory = [newRecord, ...existingHistory];
  localStorage.setItem(STORAGE_KEY, JSON.stringify(updatedHistory));
  
  return newRecord;
};

export const getHistory = () => {
  const data = localStorage.getItem(STORAGE_KEY);
  return data ? JSON.parse(data) : [];
};

// --- GENERATE PROFESSIONAL PDF ---
export const generatePDF = (record) => {
  const doc = new jsPDF();
  const p = record.patient || {}; // Access stored patient details

  // 1. Header Background
  doc.setFillColor(13, 148, 136); // Teal Color
  doc.rect(0, 0, 210, 50, 'F'); // Taller header for more info

  // 2. Title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text("Dr.Care Medical Report", 20, 20);

  // 3. Patient Details Grid (In Header)
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  
  // Column 1
  doc.text(`Patient Name: ${p.name || 'N/A'}`, 20, 32);
  doc.text(`Age: ${p.age || 'N/A'}`, 20, 38);
  doc.text(`Blood Group: ${p.bloodGroup || 'N/A'}`, 20, 44);

  // Column 2
  doc.text(`Date: ${record.date}`, 120, 32);
  doc.text(`Weight: ${p.weight ? p.weight + ' kg' : 'N/A'}`, 120, 38);
  doc.text(`Height: ${p.height ? p.height + ' cm' : 'N/A'}`, 120, 44);

  // 4. Content Body
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Patient Input / Symptoms:", 20, 65);
  
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(60, 60, 60);
  const splitSymptoms = doc.splitTextToSize(record.symptoms || "N/A", 170);
  doc.text(splitSymptoms, 20, 75);

  let nextY = 75 + (splitSymptoms.length * 7) + 15;

  // 5. Diagnosis Section
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("AI Analysis & Prescription:", 20, nextY);
  
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(40, 40, 40);
  
  // Clean up formatting for PDF
  const cleanDiagnosis = record.diagnosis.replace(/\*\*/g, '').replace(/•/g, '-');
  const splitDiagnosis = doc.splitTextToSize(cleanDiagnosis, 170);
  doc.text(splitDiagnosis, 20, nextY + 10);

  // 6. Footer
  doc.setFontSize(9);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by Dr.Care AI • Not a substitute for professional medical advice.", 105, 290, { align: "center" });

  doc.save(`DrCare_${record.type}_${record.id}.pdf`);
};